/*
  products.js
  Local catalog data for the ICMR - Global Centre of Excellence on Millets.

  - No backend, no login, no cart.
  - Add / replace items here.
  - Images live in the /product-images folder.
  - Set `image` like: "product-images/your-file.jpg".
*/

// Expose as a global for simple vanilla JS usage.
// Paste your Google Form link here later (example: "https://forms.gle/...")
window.INTEREST_FORM_URL = "";

window.PRODUCTS = [
  {
    id: "001",
    name: "Ragi (Finger Millet) Flour",
    image: "product-images/IMG-20260323-WA0000.jpg.jpeg",
    weight: "",
    category: "Flour",
    millet_type: "Ragi",
    fpo_name: "Sri Alluri Farmers Producer Organization MACS Ltd",
    fpo_location: "",
    contact: "+9194931130082",
    description: "Finger millet flour (ragi) for rotis, dosa, porridge and baking.",
    ingredients: "Finger millet (ragi)",
    shelf_life: "",
  },
  {
    id: "002",
    name: "Pink Salt",
    image: "product-images/IMG-20260323-WA0001.jpg.jpeg",
    weight: "1 kg",
    category: "Salt",
    millet_type: "Other",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "Food-grade pink salt.",
    ingredients: "Salt",
    shelf_life: "",
  },
  {
    id: "003",
    name: "Pain Relief Oil (Bottle)",
    image: "product-images/IMG-20260323-WA0003.jpg.jpeg",
    weight: "",
    category: "Personal Care",
    millet_type: "Other",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "External use only.",
    ingredients: "",
    shelf_life: "",
  },
  {
    id: "004",
    name: "Yellow Jowar Upma Rava",
    image: "product-images/IMG-20260323-WA0004.jpg.jpeg",
    weight: "400g",
    category: "Rava",
    millet_type: "Jowar",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "Coarse jowar rava for upma and breakfast recipes.",
    ingredients: "Jowar (sorghum)",
    shelf_life: "",
  },
  {
    id: "005",
    name: "Pain Relief Oil (Roll-on)",
    image: "product-images/IMG-20260323-WA0005.jpg.jpeg",
    weight: "10 ml",
    category: "Personal Care",
    millet_type: "Other",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "External use only.",
    ingredients: "",
    shelf_life: "",
  },
  {
    id: "006",
    name: "Ragi Flakes",
    image: "product-images/IMG-20260323-WA0007.jpg.jpeg",
    weight: "100g",
    category: "Flakes",
    millet_type: "Ragi",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "Ragi flakes for quick breakfasts and snacks.",
    ingredients: "Ragi (finger millet)",
    shelf_life: "",
  },
  {
    id: "007",
    name: "Ragi Idly Rava",
    image: "product-images/IMG-20260323-WA0008.jpg.jpeg",
    weight: "400g",
    category: "Rava",
    millet_type: "Ragi",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "Ragi rava for soft idli/dosa batter mixes.",
    ingredients: "Ragi (finger millet)",
    shelf_life: "",
  },
  {
    id: "008",
    name: "Karam Cashew",
    image: "product-images/IMG-20260323-WA0011.jpg.jpeg",
    weight: "",
    category: "Nuts",
    millet_type: "Other",
    fpo_name: "Prema Sai Nava Kisan Horticulture & Agriculture FPO MACS Ltd",
    fpo_location: "Anakapalli, Andhra Pradesh",
    contact: "+917671075430",
    description: "Spicy cashew snack.",
    ingredients: "",
    shelf_life: "Best before 3 months",
  },
  {
    id: "009",
    name: "Jaggery Cashew",
    image: "product-images/IMG-20260323-WA0012.jpg.jpeg",
    weight: "",
    category: "Nuts",
    millet_type: "Other",
    fpo_name: "Prema Sai Nava Kisan Horticulture & Agriculture FPO MACS Ltd",
    fpo_location: "Anakapalli, Andhra Pradesh",
    contact: "+917671075430",
    description: "Cashews coated with jaggery.",
    ingredients: "Cashew, jaggery",
    shelf_life: "Best before 3 months",
  },
  {
    id: "010",
    name: "Gongura Pickle",
    image: "product-images/IMG-20260323-WA0014.jpg.jpeg",
    weight: "",
    category: "Pickle",
    millet_type: "Other",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "Traditional gongura (sorrel leaves) style pickle.",
    ingredients: "",
    shelf_life: "",
  },
  {
    id: "011",
    name: "Salted Cashew",
    image: "product-images/IMG-20260323-WA0016.jpg.jpeg",
    weight: "",
    category: "Nuts",
    millet_type: "Other",
    fpo_name: "Prema Sai Nava Kisan Horticulture & Agriculture FPO MACS Ltd",
    fpo_location: "Anakapalli, Andhra Pradesh",
    contact: "+917671075430",
    description: "Lightly salted cashews.",
    ingredients: "Cashew, salt",
    shelf_life: "Best before 3 months",
  },
  {
    id: "012",
    name: "Wild Forest Honey",
    image: "product-images/IMG-20260323-WA0017.jpg.jpeg",
    weight: "",
    category: "Honey",
    millet_type: "Other",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "Wild forest honey from the Eastern Ghats.",
    ingredients: "Honey",
    shelf_life: "",
  },
  {
    id: "013",
    name: "Pepper Cashew",
    image: "product-images/IMG-20260323-WA0018.jpg.jpeg",
    weight: "",
    category: "Nuts",
    millet_type: "Other",
    fpo_name: "Prema Sai Nava Kisan Horticulture & Agriculture FPO MACS Ltd",
    fpo_location: "Anakapalli, Andhra Pradesh",
    contact: "+917671075430",
    description: "Pepper flavored cashews.",
    ingredients: "",
    shelf_life: "Best before 3 months",
  },
  {
    id: "014",
    name: "Sambar Powder",
    image: "product-images/IMG-20260323-WA0019.jpg.jpeg",
    weight: "",
    category: "Spices",
    millet_type: "Other",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "Spice blend for sambar.",
    ingredients: "",
    shelf_life: "",
  },
  {
    id: "015",
    name: "Traditional Pickle (Jar)",
    image: "product-images/IMG-20260323-WA0021.jpg.jpeg",
    weight: "",
    category: "Pickle",
    millet_type: "Other",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "Traditional tribal foods style pickle.",
    ingredients: "",
    shelf_life: "",
  },
  {
    id: "016",
    name: "Edible Oil",
    image: "product-images/IMG-20260323-WA0022.jpg.jpeg",
    weight: "",
    category: "Oil",
    millet_type: "Other",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "Edible oil (see label for details).",
    ingredients: "",
    shelf_life: "",
  },
  {
    id: "017",
    name: "Tribal Natural Turmeric Powder",
    image: "product-images/IMG-20260323-WA0026.jpg.jpeg",
    weight: "",
    category: "Spices",
    millet_type: "Other",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "Turmeric powder.",
    ingredients: "Turmeric",
    shelf_life: "",
  },
  {
    id: "018",
    name: "Gongura Pachadi",
    image: "product-images/IMG-20260323-WA0031.jpg.jpeg",
    weight: "",
    category: "Pickle",
    millet_type: "Other",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "Traditional pachadi style pickle.",
    ingredients: "",
    shelf_life: "",
  },
  {
    id: "019",
    name: "Flax Seeds Chilli Powder",
    image: "product-images/IMG-20260323-WA0032.jpg.jpeg",
    weight: "",
    category: "Spices",
    millet_type: "Other",
    fpo_name: "Lambasingi Tribal Products FPC Ltd",
    fpo_location: "Visakhapatnam, Andhra Pradesh",
    contact: "+9194931130082",
    description: "Flax seed + chilli powder blend.",
    ingredients: "Flax seeds, chilli",
    shelf_life: "",
  },
];
